const CONFIG = {
    titleWeb: "Gửi em",
    introTitle: 'Thế giới của anh',
    introDesc: `Anh xin lỗi em rất nhiều vì những chuyện đã xảy ra`,
    btnIntro: '^^click^^',
    title: 'Anh biết rằng em đã phải chịu đựng cũng như phải buồn rất nhiều trước cái tính trẻ con và cái lỗi suy nghĩ không đâu vào đâu của anh🥰',
    title: 'Anh biết anh đã làm em buồn nhiều như thế nào nên anh sẽ cố gắng để sửa đổi để không còn làm em buồn nữa',
    title: 'Anh mong dù là vui vẻ hay giận hờn thì chúng ta sẽ luôn cùng nhau vượt qua mọi chuyện nhé,🥰Anh Yêu Em🥰',
    desc: 'Mong em hãy tha lỗi co anh nhé!!!',
    btnYes: 'Đồng Ý <33',
    btnNo: 'Không nha :3',
    question: 'Để lại một câu nói đi nek <3',
    btnReply: 'Gửi cho bạn <3',
    reply: 'Anh yêu em nhiều lắm <3333333',
    mess: 'Anh biết mà 🥰. Anh biết em sẽ tha lỗi mà 😘😘',
    messDesc: 'Hẹn em, Vào một ngày không xa nhé.',
    btnAccept: 'Okiiiii lun <3',
}
